### ISSUE TITLE
Windows local dev guides

### ISSUE THREAD

**Issue by bertocq** [consul/docs#18]
On the windows local development section it would be nice to have links to guides for installing VirtualBox on Windows & Installing a Ubuntu VM with it like
- https://help.ubuntu.com/community/VirtualBox
- https://www.lifewire.com/run-ubuntu-within-windows-virtualbox-2202098

and the recommendation to use the Linux local dev setup guide (instead of the Windows local dev setup guide that was created by a third party in the UCM)

**Comment by javierm** [comment]
Closed via #75.
