### ISSUE TITLE
Delayed Jobs

### ISSUE THREAD

**Issue by bertocq** [consul/docs#21]
Add documentation on how to start a [DelayedJob worker](https://github.com/collectiveidea/delayed_job#running-jobs) to process asynchronous jobs

Bit of tips & links to Delayed Jobs knowledge. For example to see all current delayed jobs, on rails console `Delayed::Job.all`

**Comment by bertocq** [comment]
Sometimes forks get problems with delayedjobs (with Budget calculate_winners or Email sending). Some info from #zamora's fork that needs to be formatted and put in context:

> The hosting service doesn't keep the delayed_job daemon up so we had to create a cron to launch the delayed_jobs task every 2 minutes

```
export RAILS_ENV=production; cd ./ruby/zamoradecide ; export GEM_PATH=/home/dd285c32/ruby/gems ; export GEM_HOME=/home/dd285c32/ruby/gems ; /opt/ruby-tux/bin/ruby ./bin/delayed_job start --exit-on-complete >/dev/null 2>&1
```

> Also to manually start delayed jobs had to be from ssh terminal:
```
/opt/ruby-tux/bin/ruby ./bin/delayed_job start
```

**Comment by voodoorai2000** [comment]
To temporarily disable the queue system, modify the [configuration file](https://github.com/consul/consul/blob/master/config/initializers/delayed_job_config.rb) to have only this line:

```Delayed::Worker.delay_jobs = false```
