### ISSUE TITLE
Servers Requirements

### ISSUE THREAD

**Issue by bertocq** [consul/docs#25]
Recommended Minimum System Requirements:

```
1.Production Server:
- Distrubution: Ubuntu 16.04.3
- RAM: 32GB
- Processor: Quad core
- Hard Drive: 20 GB
- Database: Postgres

2.Staging Server:
- Distrubution: Ubuntu 16.04.3
- RAM: 16GB
- Processor: Dual core
- Hard Drive: 20 GB
- Database: Postgres
```

If your city has a population of over 1.000.000, consider balancing your load using 2-3 production servers and a separate server for the database.

**Comment by bertocq** [comment]
added at https://github.com/consul/docs/commit/012d538f3221a6840ec241b70babc2fc6f818bdb

Still pending some software configuration guidelines

**Comment by afeld** [comment]
Looks like this can be closed, given the README in https://github.com/consul/installer?

cc https://github.com/consul/installer/issues/74

**Comment by voodoorai2000** [comment]
Indeed! 😊
