### ISSUE TITLE
About documentation license?

### ISSUE THREAD

**Issue by gentooza** [consul/docs#27]
Hi wonderful team and community!

I don' t want to distract from real work, but, shouldn't we decide a license for all the documentation is being generated?

as for example [GFDL?](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License)
I think AGPL is not a valid option here, is it?

cheers! and happy hacking!
Joa

**Comment by MariaCheca** [comment]
Hi @gentooza!

Currently both [CONSUL](https://github.com/consul/consul) and [its documentation](https://github.com/consul/docs) are licensed under [GNU Affero General Public License](https://github.com/consul/docs/blob/master/LICENSE) to encourage people to use and contribute to the project freely. It's totally valid to use it in both projects, and taking into account the discussions about the GFDL compatibility with GPL and other licenses (as Apache License used by [Gitbook](https://github.com/GitbookIO/gitbook/blob/master/LICENSE)), we decided to use GPL as well for the documentation as it doesn't have this kind of drawbacks.

Thank you for your interest in Consul :) Have a nice day!

**Comment by gentooza** [comment]
well, AGPL is a software license it's not desgined for documentation as GFDL is, and GFDL is also made to: 

> encourage people to use and contribute to the project freely

and GFDL is totally compatible with any kind of GPL license, as is the **OFFICIAL** license of the GNU for documentation, so I don't understand neither these *kind drawbacks*

but ok, closed anyway!
have a really nice day you too

**Comment by bertocq** [comment]
Hello @gentooza, we're not very well versed on licenses differences, but just reading wikipedia we found [GFDL its GPL incompatible in both directions](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License#GPL_incompatible_in_both_directions) also [here](https://en.wikipedia.org/wiki/License_compatibility#GFDL_and_GPL), so please help us understand your affirmation about the topic.

Also on the [Preamble of the current License](https://github.com/consul/docs/blob/master/LICENSE) it states:

>The GNU Affero General Public License is a free, copyleft license for
software and other kinds of works

And we understand that "other kinds of works" part also covers documentation, screenshots for manuals etc... If that's not the case please help us understand why AGPLv3 is not a good idea for documentation.

**Comment by gentooza** [comment]
Hi, I' m not to versed neither, and I lacked information also :-D

It's true this incompatibilty, (I was mistake to say the opposite)

I think there shouldn't be any problem with GFDL as docs and consul are two different repositories, but AGPL is also wonderful and I suppose it makes also the trick. (and the most important is developers feeling comfortable with it)

for me it's closed, and sorry for taking your time! (I think I opened the issue more for answers than for making proposals)
cheers

**Comment by bertocq** [comment]
No problem @gentooza 👍 !!! We're sorry as well you were a little bit upset about the issue being closed. 

Something that may help understand why we kept the same (along with "we're already using it on other repo") is that we plan to include code examples (for GraphQL API, CSS customizations, etc...) on some parts of the documentation and dual licensing could be kind of messy to understand/apply for us.

Thanks for your contribution and very much welcome 😃
