### ISSUE TITLE
Document census integration

### ISSUE THREAD

**Issue by rogerpro** [consul/docs#43]
It would be great, for those of us who are deploying Consul for the first time, to have a HOWTO step by step guide to have Consul up & running.

For instance, having some tips how to run census integration explained in https://github.com/consul/consul/issues/2139

Having step by step guides will encourage more cities to use Consul for sure. And they will be more happy and have more time to improve documentation, send PR and spread the use of this app.

**Comment by javierm** [comment]
Closed via #79 and #80.

@rogerpro Thanks for reporting! :smile: I think this issue can be closed now that we've got documentation about both remote and local census integration. If you find this documentation to be innacurate or incomplete, feel free to open an issue, or, even better, a pull request :wink:.
