### ISSUE TITLE
Production environment initial configuration

### ISSUE THREAD

**Issue by voodoorai2000** [consul/docs#46]
There are some things to do when you first launch an application in the production environment.

Here are the questions that forks are asking:

**How to create an admin?**

- First you will need to register a standard user account
- Then in the [rails console](http://guides.rubyonrails.org/command_line.html#rails-console) these commands should make that user an admin:

```
user = User.where(email: "your_email_address").first
Administrator.create(user: user)
```

**Comment by javierm** [comment]
Closing since we're about to archive this repository.
