### ISSUE TITLE
Add NodeJS as prerequisite

### ISSUE THREAD

**Issue by bertocq** [consul/docs#50]
As noted by @aitbw at https://github.com/consul/consul/pull/2486 we should include NodeJS as a requirement on all `/getting_started/prerequisites` guides.

**Comment by aitbw** [comment]
One step ahead of you, @bertocq, I'm already working on it updating both English and Spanish docs accordingly :smile:

Just one thing I'd like to discuss: Preferred method to install Node.js? I'm currently using [tj/n](https://github.com/tj/n) and works flawlessly but it'd be better if we could discuss it first :relieved:

**Comment by bertocq** [comment]
Awesome @aitbw  👏. As you know I'm not very up to date with JS environment, and just use [nvm](https://github.com/creationix/nvm) because someone said so somewhere... but whatever the nodejs community has as a good standard would do :).

I think both `rbenv` and `rvm` are okey at Ruby community, but we're explicitly mentioning only `rbenv` at macos documentation because thats the combination we all use :( Maybe we should be more clear anything that installs the right version of ruby would be 👌 ... and same should be applied to NodeJS 🤔 ... but anything would be far better than what we have right now (no mention whatsoever to nodejs 😞 )

Thanks!
