### ISSUE TITLE
Delayed jobs for email delivery

### ISSUE THREAD

**Issue by voodoorai2000** [consul/docs#54]
What
===
Add documentation on how to start a [DelayedJob worker](https://github.com/collectiveidea/delayed_job#running-jobs) to process asynchronous jobs

Why
===
All emails are delivered asynchronously through the queue system

Notes
===
To temporarily disable the queue system and send emails synchronously
https://github.com/consul/docs/issues/21#issuecomment-356722390

**Comment by bertocq** [comment]
Algunas de mis notas sobre esto:

Para lanzar el demonio debería ser con este comando, desde la carpeta de la aplicación:

`RAILS_ENV=preproduction bin/delayed_job start`

Si da problemas… también se puede quitar la cola cambiando este archivo:
  https://github.com/consul/consul/blob/master/config/initializers/delayed_job_config.rb#L1 Y poniendo por ejemplo sólo `Delayed::Worker.delay_jobs = false`

**Comment by javierm** [comment]
I'm merging the contents of this issue with issue #21.
