### ISSUE TITLE
Install Consul  Ansible: task capistrano fails  

### ISSUE THREAD

**Issue by jesuxgslp** [consul/docs#55]
Just flowing the instillation instructions  

TASK [capistrano : Copy deploy.rb (locally)] ***************************************************************************************************************************************************************
fatal: [10.99.52.80]: FAILED! => {"changed": false, "checksum": "df14b6d8a11dd21c701813c32e1da2b6548c5e69", "dest": "/home/user/projects/installer/consul/config/deploy.rb", "gid": 1000, "group": "user", "mode": "0644", "msg": "chgrp failed: failed to look up group wheel", "owner": "deploy", "path": "/home/user/projects/installer/consul/config/deploy.rb", "size": 1922, "state": "file", "uid": 1001}
	to retry, use: --limit @/home/user/projects/installer/consul.retry

**Comment by javierm** [comment]
I've never seen this error :thinking:.

In any case, we've just updated the capistrano setup and instructions in the installer :smile:. If you're still experiencing this problem, feel free to open in an issue in the [installer repository](https://github.com/consul/installer).
