### ISSUE TITLE
Broken links to images

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/docs#57]
URL: https://consul_docs.gitbooks.io/docs/content/en/getting_started/dev_mailserver.html

Is: ../../**mailserver/img**/development.rb.png
Should be: ../../**img/mailserver**/development.rb.png

And a few other images apart from this one have broken links on this page.

**Comment by javierm** [comment]
Closed via commit fca38280 from pull request #89.

@KrzysztofMadejski Thanks for reporting! :smile:.
