### ISSUE TITLE
question about alternative deployment methods

### ISSUE THREAD

**Issue by gentooza** [consul/docs#58]
Hi!

First I want to clarify I make this question from ignorance, and willing to improve.

I've installing Consul by a different method than docker, and I'd know advantages or disadvantages thinking about security first, and ease of maintenance.

In only few steps:
- we had to configure previously as administrator postgresql, of course, and some dependencies as nodejs, etc. (but standard with package manager) 
- install rvm as local user in server
- install ruby version locally again by rvm, only for user
- make bundle, etc.
- we use passenger, installed as root via package manager.
- finally we have to tweak a little bit the apache .vhost for passenger executing the user ruby version, ssl...

it takes half an hour so far.

I think system is enough isolated, and can be easily maintained. (truly I know nothing about docker, and I should try it out soon) (also, have Consul upgraded depends of local user, and .vhost will have to be upgraded when the ruby version changes :-/)

thanks for sharing your knowledge!
best regards,
Joaquín

**Comment by javierm** [comment]
@gentooza Sorry for the late reply!

I'm afraid I'm not sure what the question is :thinking:.

Anyway, for questions like this one, maybe it's better to ask in the #tech-questions channel in our slack, or in our community.

By the way, we've now got a installer (https://github.com/consul/installer) which automates the process you mention :smile:. You may want to check it out.
