### ISSUE TITLE
Dead link in customization introduction

### ISSUE THREAD

**Issue by PierreMesure** [consul/docs#62]
I don't have time now to clone the repo and test what works but the link to the page Fork your repo doesn't work on [this page](https://consul_docs.gitbooks.io/docs/content/en/customization/introduction.html). It should be [https://consul_docs.gitbooks.io/docs/content/en/forks/create.html](https://consul_docs.gitbooks.io/docs/content/en/forks/create.html).

I guess we could use `../forks/create.md`?

**Comment by javierm** [comment]
Thanks for reporting! Closed via commit 7a2078d2 from pull request #89.
