### ISSUE TITLE
Update documentation for email in development

### ISSUE THREAD

**Issue by afeld** [consul/docs#64]
[The documentation](https://consul_docs.gitbooks.io/docs/content/en/getting_started/dev_mailserver.html) suggests using Mailgun, but setting up a real email service for development runs the risk of spamming users. You might consider suggesting an alternative that "catches" the outgoing emails:

* [MailCatcher](https://mailcatcher.me/)
* [MailTrap](https://mailtrap.io/)
* [MailHog](https://github.com/mailhog/MailHog)
* [Letter Opener](https://github.com/ryanb/letter_opener)

**Comment by voodoorai2000** [comment]
Nice catch @afeld  😌

We do use [Letter Opener](https://github.com/consul/consul/blob/master/config/routes.rb#L10) for [development environments](https://github.com/consul/consul/blob/master/config/environments/development.rb#L22). 

Indeed that documentation might not be appropriate, real email deliveries should probably only be encouraged in the staging and production servers.
