### ISSUE TITLE
Manual installation on production

### ISSUE THREAD

**Issue by jfoclpf** [consul/docs#98]
I don't want to use the installer cause I have a bunch of other important stuff running on my server, and I can deal with nginx, SSL, passenger, postgre, unix, etc. but my problem is really ruby on rails, which I don't get a clue (my world is NodeJS), so I just follow strictly your documentation.

The [manual instructions for development installation](https://docs.consulproject.org/docs/english-documentation/introduction/local_installation) are quite simple and effective, it took me just 10 minutes to implement them and make the site online. But I am here for **more than 5 hours** to try to implement the production and I just get errors and more errors. 

Pleeeeeeeease make a simple tutorial on how to make the deployment of production

I tried several commands and combinations like `bundle install --deployment` and then `bin/rake db:migrate RAILS_ENV=production` and I can't make it work.

A manual installation on production, preferably for Ubuntu 18.04, is highly appreciated.

**Comment by javierm** [comment]
Hi, @jfoclpf :smile:

> The manual instructions for development installation are quite simple and effective, it took me just 10 minutes to implement them and make the site online.

Instructions are simple because an installation on a development machine is easy :smile:.

> But I am here for more than 5 hours to try to implement the production and I just get errors and more errors.

Because an installation on a production machine is hard :relieved:. That's why we wrote the installer.

I understand the frustration. However, please take into account that you're trying to do something that we don't officially support :pray:.

First of all, we strongly recommend that, for production sites, you use a dedicated server. Most of the time, that's perfectly possible.

If that's 100% out of the question, try checking the installer's code and manually follow the same steps it executes and skip the ones you consider unnecessary in your case. As an alternative, search for tutorials about configuring Ruby on Rails with Nginx on production environments.

Hope that helps!

**Comment by jfoclpf** [comment]
Hi @javierm 
thanks again for the reply, yes, I am very frustrated :smile: 

I really don't understand what am I missing. When I look at the installer it mentions a lot of things that are already working fine on me, like nginx, SSL or letsencrypt, or accessing a remote server, I don't need to implement nothing of that. I have a mailgun account and thus mail server is not an issue either. I can configure all of that easily, including the APIs from facebook or google to login. I have a fully functional server with Ubuntu 18.04 with all the needed packages. My problem is really just ruby on rails. 

>I understand the frustration. However, please take into account that you're trying to do something that we don't officially support

Just tell me the commands on RoR to make the site online on production (ignore nginx, mail server, ssl,  etc.). 
Of course I will never complain if anything goes wrong, this is open source, no liabilities involved.

>try checking the installer's code and manually follow the same steps it executes and skip the ones you consider unnecessary

If it's not asking too much, can you point me exactly which file it is, I can't find it on the repo

**Comment by javierm** [comment]
Hi, @jfoclpf :smile:.

Hang in there! It might take longer than you hoped for, but I'm sure you'll manage to do it.

The Ruby on Rails setup is configured in the `roles/folder_structure/`, `roles/ruby/`, `roles/rails/`, `roles/email/`, `roles/queue/` and `roles/puma/` folders. There's also an nginx configuration file at `roles/nginx/templates/consul_vhost.j2` you might want to check; particularly the line configuring the puma socket.

The installer configures nginx with puma; not passenger. I'm afraid my latest experience with Passenger and Rails was back in 2013, so I don't think I'll be able to help here. You could try asking whether someone else has configured Passenger and could assist you on [our community](https://community.consulproject.org/) or [our slack channels](https://consul.slack.com/) (feel free to request an invitation if you need it).

**Comment by jfoclpf** [comment]
Hi @javierm 
I got it, it's working :)

no need for puma, I am using passenger with nginx

I just had to generate the secret with  `bin/rake secret RAILS_ENV=production` and copy it to the `config/secrets.yml` and then run further

```
bin/rake db:migrate RAILS_ENV=production
bin/rake db:seed RAILS_ENV=production
bin/rake assets:precompile RAILS_ENV=production
```

can you just give a look?
https://decidelisboa.org/
images are missing though

**Comment by javierm** [comment]
Glad it's working! Not sure about the missing images; maybe something is still running in the development environment :thinking:.

If you want to change the code and deploy it to the production server, we recommend [deploying with Capistrano](https://github.com/consul/installer#deploys-with-capistrano). You'd have to change the `config/deploy.rb` file to use your repository and, in your case, remove the calls to `puma:start` and `puma:restart` and replace them with something which touches the `tmp/restart.txt` file (I take it passenger is still restarted this way?).

By the way, would you mind sending a brief [email to the CONSUL Democracy Foundation](mailto:info@consulfoundation.org) with information regarding the project? Experiences and purposes behind CONSUL installations are always welcome and help improving the project :smile:.

**Comment by jfoclpf** [comment]
sure, I will send the email, but I think my production deploy is a bit messy yet :) 

I really could not understand the [directory structure](https://github.com/consul/installer/blob/master/roles/folder_structure/tasks/main.yml) (too many different directories with links in between) thus I am still using the normal `public/` directory which comes in dev mode.

If you want I can make a PR to documentation on how to do the production manual installation, considering the user is already aware of nginx, SSL, mail server, etc. making a initial note that it is not recommended and that they should use the installer instead, which is recommended.

**Comment by javierm** [comment]
A pull request would be awesome. Thanks a lot! :pray:

You can read at Capistrano's website about [Capistrano's structure](https://capistranorb.com/documentation/getting-started/structure/). The main point is that every time you deploy a new version, a new folder is created with that version (that way you can easily roll back) and some files are shared among versions (like files users/admins attach when using the application).

**Comment by jfoclpf** [comment]
> A pull request would be awesome. Thanks a lot! 

Done it https://github.com/consul/docs/pull/99
[Here nicely seen](https://github.com/consul/docs/pull/99/files?short_path=d6c60fe#diff-d6c60fec35efc084608e6b2ee3b7aafcaf58f0652dc30da9b27bcc033005a556)

> You can read at Capistrano's website about [Capistrano's structure](https://capistranorb.com/documentation/getting-started/structure/). The main point is that every time you deploy a new version, a new folder is created with that version (that way you can easily roll back) and some files are shared among versions (like files users/admins attach when using the application).

Ok, I take a look, but which commands should I run specifically?

**Comment by jfoclpf** [comment]
Anyway I don't think I will ever edit the code because I do not domain ruby at all, that's not my world, my world is Javascript/NodeJS. I just want to fetch new updates from the main repo. How will that work?

**Comment by jfoclpf** [comment]
I realised now that the first release directory that I create does not confirm the time tag from Capistrano, I have to amend that later on.

**Comment by javierm** [comment]
In the release notes of new consul versions we add instructions about how to update your repo with the new code. But deploying it to the production server is up to you; again, we recommend Capistrano.

**Comment by jfoclpf** [comment]
>again, we recommend Capistrano

But even with Capistrano, if you don't want to use the installer for production, I still think my PR is very useful (you have of course to double-check it)

> In the release notes of new consul versions we add instructions about how to update your repo with the new code

Thank you, I will check it out

**Comment by jfoclpf** [comment]
I closed this issue, but please take a look on my PRs ;)
